---
AWSTemplateFormatVersion: '2010-09-09'
Description: creates an instance
Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  InstanceType:
    Type: String
    Default: t2.micro
  VpcId:
    Type: AWS::EC2::VPC::Id    
  SubnetId: 
    Type: AWS::EC2::Subnet::Id
Mappings:
  RegionMap:
    ap-east-1:
      ami: ami-868bcff7	
    ap-northeast-1: 
      ami: ami-01f90b0460589991e
    ap-northeast-2:
      ami: ami-096e3ded41e3bda6a
    ap-northeast-3:
      ami: ami-0942fd36e1571cbdf
    ap-south-1:
      ami: ami-0d11056c10bfdde69
    ap-southeast-1:
      ami: ami-07ce5f60a39f1790e
    ap-southeast-2:
      ami: ami-04c7af7de7ad468f0
    ca-central-1:
      ami: ami-064efdb82ae15e93f
    cn-north-1:
      ami: ami-01993b4213b4bffb5
    cn-northwest-1:
      ami: ami-01d4e30d4d4952d0f
    eu-central-1:
      ami: ami-0718a1ae90971ce4d
    eu-north-1:
      ami: ami-0e850e0e9c20d9deb
    eu-west-1:
      ami: ami-07042e91d04b1c30d
    eu-west-2:
      ami: ami-04cc79dd5df3bffca
    eu-west-3:
      ami: ami-0c367ebddcf279dc6
    me-south-1:
      ami: ami-0e40363f9ed76073b
    sa-east-1:
      ami: ami-0cb1ddea3786f6c0d
    us-east-1:
      ami: ami-046842448f9e74e7d
    us-east-2:
      ami: ami-0367b500fdcac0edc
    us-gov-east-1:
      ami: ami-40749631
    us-gov-west-1:
      ami: ami-dffbd8be
    us-west-1:
      ami: ami-0d58800f291760030
    us-west-2:
      ami: ami-0edf3b95e26a682df
Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:       
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", ami]
      InstanceType: !Ref InstanceType      
      KeyName: !Ref KeyName
      SecurityGroupIds: 
        - !GetAtt SecurityGroup.GroupId
      SubnetId: !Ref SubnetId

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: security group for interview instance
      VpcId: !Ref VpcId 

Outputs:
  PublicIp:
    Value: !GetAtt Instance.PublicIp
